# Generated by Django 2.0.5 on 2019-01-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(default='main', max_length=100)),
                ('size', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('price', models.PositiveSmallIntegerField()),
                ('numberOfPeople', models.PositiveSmallIntegerField(default=1)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_Has_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Building')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_Payment',
            fields=[
                ('paymentId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('isCash', models.BooleanField()),
                ('date', models.DateField()),
                ('creditCard', models.CharField(blank=True, max_length=30, null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Customer')),
                ('reservationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('floor', models.PositiveSmallIntegerField()),
                ('beds', models.PositiveSmallIntegerField(default=1)),
                ('view', models.CharField(max_length=20)),
                ('hasBalcony', models.BooleanField()),
                ('isClean', models.BooleanField()),
                ('buildingName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unitId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='unitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Unit'),
        ),
        migrations.AddField(
            model_name='reservation_has_room',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Room'),
        ),
        migrations.AddField(
            model_name='reservation_has_room',
            name='reservationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Reservation'),
        ),
        migrations.AddField(
            model_name='reservation_has_room',
            name='unitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Unit'),
        ),
        migrations.AddField(
            model_name='building',
            name='unitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Unit'),
        ),
    ]
