# Generated by Django 2.0.5 on 2019-01-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_has_room',
            name='buildingName',
        ),
        migrations.RemoveField(
            model_name='reservation_has_room',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='reservation_has_room',
            name='unitId',
        ),
        migrations.RemoveField(
            model_name='reservation_payment',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='room',
            name='unitId',
        ),
    ]
