# Generated by Django 2.0.5 on 2019-01-12 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20190112_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_has_room',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2019, 1, 12, 14, 18, 29, 808980, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation_has_room',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2019, 1, 12, 14, 18, 37, 42305, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
