# Generated by Django 2.0.5 on 2019-01-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20190112_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservationId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
