# Generated by Django 2.0.5 on 2019-01-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20190113_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation_payment',
            name='paymentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
